### ISSUE TITLE
Легенда карты

### ISSUE THREAD

**Issue by vacmannnn** [TimPushkin/DepNav#32]
Некоторые обозначения интуитивно непонятны, например звездочки и стрелочки вверх. Было бы удобнее иметь легенду карты.

**Comment by TimPushkin** [comment]
Спасибо за интерес к DepNav!

В идеале хотелось бы сделать такие обозначения, чтобы они не требовали легенды. В данный момент в приложении используются эмоджи от Твиттера, и, к сожалению, в них не все категории значков можно идеально обозначить. Если есть какие-либо предложения, я бы с радостью обсудил. Если ничего не придумаю, то действительно добавлю легенду.

Сейчас уже готовлю достаточно крупное обновление, так что только с этим разберусь уже после него. Пока поясню словами:
- Стрелки вверх, вниз, вверх-вниз -- лестницы на другие этажи в соответствующем направлении
-- Звёздочки -- объекты, не попадающие ни в одну другую категорию (то есть, не лестницы, лифты, аудитории, туалеты, входы), понять, что это такое, всегда можно, нажав по ним и прочитав название / описание

**Comment by TimPushkin** [comment]
Поменял иконки на, надеюсь, более понятные, плюс добавил-таки легенду. Будет в следующем релизе.

![image](https://github.com/TimPushkin/DepNav/assets/71890197/723606db-23d4-443b-9251-756a0fbc1f3a)
